In [1]:
# here we want to understand which features are strongly associated to survived-yes,eg.if 1st class,male->yes OR female->yes
# install 'mlxtend' library if not insatlled already
!pip install mlxtend

Requirement already satisfied: mlxtend in /usr/local/lib/python3.10/dist-packages (0.23.1)
Requirement already satisfied: scipy>=1.2.1 in /usr/local/lib/python3.10/dist-packages (from mlxtend) (1.13.1)
Requirement already satisfied: numpy>=1.16.2 in /usr/local/lib/python3.10/dist-packages (from mlxtend) (1.26.4)
Requirement already satisfied: pandas>=0.24.2 in /usr/local/lib/python3.10/dist-packages (from mlxtend) (2.1.4)
Requirement already satisfied: scikit-learn>=1.0.2 in /usr/local/lib/python3.10/dist-packages (from mlxtend) (1.3.2)
Requirement already satisfied: matplotlib>=3.0.0 in /usr/local/lib/python3.10/dist-packages (from mlxtend) (3.7.1)
Requirement already satisfied: joblib>=0.13.2 in /usr/local/lib/python3.10/dist-packages (from mlxtend) (1.4.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.2.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.0->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.0->mlxtend) (4.53.1)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.0->mlxtend) (1.4.5)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.0->mlxtend) (24.1)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.0->mlxtend) (9.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.0->mlxtend) (3.1.4)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.10/dist-packages (from matplotlib>=3.0.0->mlxtend) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.24.2->mlxtend) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.24.2->mlxtend) (2024.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn>=1.0.2->mlxtend) (3.5.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.16.0)

In [2]:
import mlxtend

In [5]:
import pandas as pd
from mlxtend.frequent_patterns import apriori,association_rules
from mlxtend.preprocessing import TransactionEncoder

In [6]:
titanic=pd.read_csv("/content/Titanic.csv")
titanic

     Class  Gender    Age Survived
0      3rd    Male  Child       No
1      3rd    Male  Child       No
2      3rd    Male  Child       No
3      3rd    Male  Child       No
4      3rd    Male  Child       No
...    ...     ...    ...      ...
2196  Crew  Female  Adult      Yes
2197  Crew  Female  Adult      Yes
2198  Crew  Female  Adult      Yes
2199  Crew  Female  Adult      Yes
2200  Crew  Female  Adult      Yes

[2201 rows x 4 columns]

In [7]:
 titanic["Class"].value_counts()

Class
Crew    885
3rd     706
1st     325
2nd     285
Name: count, dtype: int64

In [8]:
 titanic["Gender"].value_counts()

Gender
Male      1731
Female     470
Name: count, dtype: int64

In [9]:
 titanic["Age"].value_counts()

Age
Adult    2092
Child     109
Name: count, dtype: int64

In [10]:
 titanic["Survived"].value_counts()

Survived
No     1490
Yes     711
Name: count, dtype: int64

# **Pre-Processing**

In [11]:
 df=pd.get_dummies(titanic)
 df

      Class_1st  Class_2nd  Class_3rd  Class_Crew  ...  Age_Adult  Age_Child  Survived_No  Survived_Yes
0         False      False       True       False  ...      False       True         True         False
1         False      False       True       False  ...      False       True         True         False
2         False      False       True       False  ...      False       True         True         False
3         False      False       True       False  ...      False       True         True         False
4         False      False       True       False  ...      False       True         True         False
...         ...        ...        ...         ...  ...        ...        ...          ...           ...
2196      False      False      False        True  ...       True      False        False          True
2197      False      False      False        True  ...       True      False        False          True
2198      False      False      False        True  ...       True      False        False          True
2199      False      False      False        True  ...       True      False        False          True
2200      False      False      False        True  ...       True      False        False          True

[2201 rows x 10 columns]

# **Apriori algorithm**

In [13]:
frequent_items=apriori(df,min_support=0.1,use_colnames=True) # min_support default value is 0.5
#min_support is a float b/w 0 and 1 for minimum support of the itemsetsreturned
# the support is computed as the fraction transactions_where_item(s)_occur / total_transactions
frequent_items # o/p is frequent itemsets: 1-item itemsets,2-item itemsets etc.with min-support criteria

     support                                           itemsets
0   0.147660                                        (Class_1st)
1   0.129487                                        (Class_2nd)
2   0.320763                                        (Class_3rd)
3   0.402090                                       (Class_Crew)
4   0.213539                                    (Gender_Female)
5   0.786461                                      (Gender_Male)
6   0.950477                                        (Age_Adult)
7   0.676965                                      (Survived_No)
8   0.323035                                     (Survived_Yes)
9   0.144934                             (Age_Adult, Class_1st)
10  0.118582                             (Class_2nd, Age_Adult)
11  0.231713                           (Class_3rd, Gender_Male)
12  0.284871                             (Age_Adult, Class_3rd)
13  0.239891                           (Survived_No, Class_3rd)
14  0.391640                          (Class_Crew, Gender_Male)
15  0.402090                            (Class_Crew, Age_Adult)
16  0.305770                          (Survived_No, Class_Crew)
17  0.193094                         (Age_Adult, Gender_Female)
18  0.156293                      (Survived_Yes, Gender_Female)
19  0.757383                           (Age_Adult, Gender_Male)
20  0.619718                         (Survived_No, Gender_Male)
21  0.166742                        (Survived_Yes, Gender_Male)
22  0.653339                           (Survived_No, Age_Adult)
23  0.297138                          (Survived_Yes, Age_Adult)
24  0.209905                (Age_Adult, Class_3rd, Gender_Male)
25  0.191731              (Survived_No, Class_3rd, Gender_Male)
26  0.216265                (Survived_No, Age_Adult, Class_3rd)
27  0.391640               (Class_Crew, Age_Adult, Gender_Male)
28  0.304407             (Survived_No, Class_Crew, Gender_Male)
29  0.305770               (Survived_No, Age_Adult, Class_Crew)
30  0.143571           (Survived_Yes, Age_Adult, Gender_Female)
31  0.603816              (Survived_No, Age_Adult, Gender_Male)
32  0.153567             (Survived_Yes, Age_Adult, Gender_Male)
33  0.175829   (Survived_No, Age_Adult, Class_3rd, Gender_Male)
34  0.304407  (Survived_No, Age_Adult, Class_Crew, Gender_Male)

In [14]:
rules=association_rules(frequent_items,metric="lift",min_threshold=0.7)# min_threshold is confidence
rules
rules.sort_values("lift",ascending=False)[0:20]

                               antecedents  ... zhangs_metric
66              (Age_Adult, Gender_Female)  ...      0.700873
67                          (Survived_Yes)  ...      0.835403
19                         (Gender_Female)  ...      0.710327
18                          (Survived_Yes)  ...      0.825219
69                         (Gender_Female)  ...      0.709577
64               (Survived_Yes, Age_Adult)  ...      0.793974
100               (Age_Adult, Gender_Male)  ...      0.986022
97               (Survived_No, Class_Crew)  ...      0.344592
48                (Age_Adult, Gender_Male)  ...      0.916706
49                            (Class_Crew)  ...      0.371976
52               (Survived_No, Class_Crew)  ...      0.302519
57                           (Gender_Male)  ...      0.983509
105                          (Gender_Male)  ...      0.983509
92    (Survived_No, Age_Adult, Class_Crew)  ...      0.302519
104                           (Class_Crew)  ...      0.338549
93   (Survived_No, Age_Adult, Gender_Male)  ...      0.510929
11                           (Gender_Male)  ...      0.901730
10                            (Class_Crew)  ...      0.322047
51                           (Gender_Male)  ...      0.901730
46                 (Class_Crew, Age_Adult)  ...      0.322047

[20 rows x 10 columns]

In [15]:
rules[rules.lift>1]

/usr/local/lib/python3.10/dist-packages/pandas/core/nanops.py:1010: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

                   antecedents                             consequents  ...  conviction  zhangs_metric
0                  (Age_Adult)                             (Class_1st)  ...    1.005694       0.639010
1                  (Class_1st)                             (Age_Adult)  ...    2.682493       0.037128
8                (Survived_No)                             (Class_3rd)  ...    1.052040       0.293515
9                  (Class_3rd)                           (Survived_No)  ...    1.281251       0.139592
10                (Class_Crew)                           (Gender_Male)  ...    8.216621       0.322047
..                         ...                                     ...  ...         ...            ...
101  (Class_Crew, Gender_Male)                (Survived_No, Age_Adult)  ...    1.556362       0.262074
102              (Survived_No)    (Class_Crew, Age_Adult, Gender_Male)  ...    1.105434       0.399458
103                (Age_Adult)  (Survived_No, Class_Crew, Gender_Male)  ...    1.023334       1.000000
104               (Class_Crew)   (Survived_No, Age_Adult, Gender_Male)  ...    1.630802       0.338549
105              (Gender_Male)    (Survived_No, Age_Adult, Class_Crew)  ...    1.132622       0.983509

[74 rows x 10 columns]